/**
 * Seeds the admin user and imports the articles that used to be hard-coded in
 * src/lib/data.js.
 *
 * Safe to re-run: the user is upserted and an article is skipped when its slug
 * is already in the database, so edits made in the admin panel are never
 * overwritten.
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * src/lib/data.js is generated by generate-data.js, which writes the array with
 * JSON.stringify — so the slice between the opening bracket and the closing
 * `];` parses as JSON. Reading it as text avoids loading an ES module from a
 * CommonJS package.
 */
async function readLegacyArticles() {
  const file = path.join(process.cwd(), "src", "lib", "data.js");
  const source = await readFile(file, "utf8");

  const start = source.indexOf("[", source.indexOf("sampleArticles"));
  const end = source.indexOf("\n];", start);
  if (start === -1 || end === -1) {
    throw new Error("Could not find the sampleArticles array in src/lib/data.js");
  }

  return JSON.parse(source.slice(start, end + 2));
}

async function seedAdmin() {
  const email = (process.env.ADMIN_EMAIL || "admin@manbayee.com").toLowerCase();
  const password = process.env.ADMIN_PASSWORD || "manbayee@123";
  const name = process.env.ADMIN_NAME || "Manbayee Admin";

  const user = await prisma.user.upsert({
    where: { email },
    update: { name, role: "ADMIN", status: "ACTIVE" },
    create: { email, name, role: "ADMIN", passwordHash: await bcrypt.hash(password, 10) },
  });

  console.log(`Admin user ready: ${email}`);
  return user;
}

async function seedArticles(authorUserId) {
  const legacy = await readLegacyArticles();
  const existing = new Set(
    (await prisma.article.findMany({ select: { slug: true } })).map((a) => a.slug)
  );

  let imported = 0;

  for (const item of legacy) {
    // The old numeric id becomes the slug, so /katurai/1 … /katurai/179 keep
    // resolving after the import.
    if (existing.has(String(item.id))) continue;

    const publishedAt = new Date(item.date);

    await prisma.article.create({
      data: {
        slug: String(item.id),
        title: item.title,
        division: item.division,
        category: item.category,
        author: item.author || "நிர்வாகம்",
        content: item.content,
        image: item.image || null,
        views: Number(item.views) || 0,
        publishedAt: Number.isNaN(publishedAt.getTime()) ? new Date() : publishedAt,
        status: "PUBLISHED",
        authorUserId,
      },
    });

    imported += 1;
  }

  console.log(`Articles imported: ${imported} (${legacy.length - imported} already present)`);
}

async function main() {
  const admin = await seedAdmin();
  await seedArticles(admin.id);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
